app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function ()
{
    return view('welcome');
});


Route::group(['middleware' => ['web']], function ()
{
    // Group Routes
    Route::resource('client', 'ClientController');
    Route::resource('project', 'ProjectController');
    Route::resource('shoot', 'ShootController');
    Route::resource('photo', 'PhotoController');
});


// Route::group(['middleware' => 'web'], function () {
//     Route::get('bar', function () {
//         return csrf_token(); // works
//     });
// });

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function ()
{
    //
});

app/Project.php
<?php

namespace Snapshot;

use Illuminate\Database\Eloquent\Model;
// Bootsttrapper Classes
use Bootstrapper\Facades\Accordion as Accordion;
// Sluggable
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

use Snapshot\SnapshotTraits as SnapshotTraits;

/**
 * Class Project
 * This Model defines a Project which contains many Shoots.
 * Projects belong to Clients.
 *
 * @package snapshot
 */
class Project extends Model implements SluggableInterface {
    use SnapshotTraits;
    use SluggableTrait;

    /** @var array Model Attributes which should be treated as dates */
    protected $dates = ['deadline'];

    /**
     * Converts the Project name to a URL slug.
     * (http://url.com/project-name)
     *
     * @var array
     */
    protected $sluggable = array(
        "build_from" => "name",
        "save_to"    => "slug",
    );

    /**
     * Defines a one to many relationship between Client and Project.
     * (many Projects are carried out for one Client)
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function client()
    {
        return $this->belongsTo('Snapshot\Client');
    }

    /**
     * Defines a one to many relationship with Shoots.
     * (one Project has many Shoots)
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function shoots()
    {
        return $this->hasMany('Snapshot\Shoot');
    }

    /**
     * Defines a one to one relationship for comments.
     * (one Project has a single Comment)
     * @method comments
     *
     * @return Snapshot\Comment   This project's comment.
     */
    public function comments()
    {
        return $this->morphOne('\Snapshot\Comment', 'commentable');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace Snapshot\Http\Controllers;

use Snapshot\Http\Requests\ProjectFormRequest;

use Illuminate\Http\Request;

use Snapshot\Http\Requests;
use Snapshot\Http\Controllers\Controller;

use Snapshot\Project as Project;
use Snapshot\Client as Client;
use Snapshot\Comment as Comment;
use Snapshot\SnapshotTraits as SnapshotTraits;

class ProjectController extends Controller {
    use SnapshotTraits;

    public function index(Request $request)
    {
        $client_id = $request->input('client_id');
        if ($client_id) {
            $projects = Project::with('client', 'shoots')->where('client_id', $client_id)->get();
        } else {
            $projects = Project::with('client', 'shoots')->get();
        }
        return view('project.index')->with('projects', $projects);
    }

    public function show($slug)
    {
        // $slugged = Project::findBySlug($slug);
        $project = Project::with('client', 'shoots')->where('slug', $slug)->get();
        $project = $project[0];

        return view('project.show')->with('project', $project);
    }

    public function create()
    {
        $clients = Client::all();

        return view('project.create')->with('clients', $clients);
    }

    public function edit($slug)
    {
        $project = Project::findBySlug($slug);

        return view('project.edit')->with('project', $project);
    }

    public function store(ProjectFormRequest $request)
    {
        // Create a new Project object
        $project = new Project;
        $project = $this->makeProject($project, $request);
        $project->save();
        // If there's a project comment, add it to the comments table.
        $this->saveComment($project, $request);

        // Redirect to the newly created projects page.
        return \Redirect::route('project.show', array('slug' => $project->slug))->with('message', "$project->name was created. ");
    }

    public function update($id, ProjectFormRequest $request)
    {
        // // Get the project from the database and update fields.
        $project = Project::findBySlug($id);
        $project = $this->makeProject($project, $request);
        // // Update the project
        $project->update();
        // // If there's a submitted comment, update or save it it in the comments table.
        $this->updateComment($project, $request);

        // Redirect to the newly created projects page.
        return \Redirect::route('project.show', array('slug' => $project->slug))->with('message', "$project->name was updated. ");
    }

    public function destroy($id)
    {
        // // Get the project from the database to create the message.
        $project = Project::find($id);
        $message = $project->name . " was deleted.";
        // // Delete the cient
        Project::destroy($id);

        // // Redirect to the project index.
        return \Redirect::route('project.index')->with('message', $message);
    }
}

resources/views/project/create.blade.php
@extends('layouts.master', ["pageTitle" => "Add Client", "subTitle" => "New Project"])

@section('content')
  {!! Form::open(array(
    'route' => 'project.store',
    'class' => 'form'
  ))!!}
  @include('project.partials.form' )

  {!! Button::primary('Create Project!')->submit()->block()!!}
  {!! Form::close() !!}
@endsection

resources/views/project/delete.blade.php
@extends('layouts.master')

@section('content')
  <h2>Delete</h2>
  {{-- @include('client.partials.index-table', array('clients' => $clients)) --}}
@endsection

resources/views/project/edit.blade.php
@extends('layouts.master', ["pageTitle" => "Edit Project", "subTitle" => $project->name])

@section('content')
  {!! Form::model($project, array(
    'method'=> 'put',
    'route' => ['project.update', $project->slug],
    'class' => 'form',
  )) !!}

  {{ Session::get('message') }}

  @include('project.partials.form')
  {!! Button::primary('Update Project')->submit()->block()!!}
  {!! Form::close() !!}
@endsection

resources/views/project/index.blade.php
@extends('layouts.master', ['pageTitle' => 'Projects', 'subTitle' => 'All Projects'])
@section('content')
<section id="selector">
  @include('partials.form.client-selector')
</section>

<section class="project-list">
  @include('project.partials.index-table', ['projects' => $projects, 'cols' => 4])
</section>
@endsection


@section('scripts')

<script>
$selector = $('#selector');
$clientSelector = $selector.find('.form-control');
$clientSelector.on('change', function() {
  console.log($clientSelector.val());
  window.location.replace("project?client_id=" + $clientSelector.val() );
})

</script>

@endsection

resources/views/project/show.blade.php
@extends('layouts.master', ["pageTitle" => "Project", "subTitle" => $project->name])

@section('content')
  <section class="actions">
    {!! $project->btn_edit()!!}
    {!! $project->btn_delete()!!}
  </section>

<section class="col-md-8 container index">
      <h3> Shoots </h3>

      @if( $project->shoots->count() )
        @include('shoot.partials.index-table', ['shoots' => $project->shoots, 'cols' => 6])
      @else
        <p> There are no shoots for this project. </p>
        <p> {!! HTML::link(\URL::route('shoot.create') . "?project_id=$project->id&client_id=" . $project->client->id, 'Add a shoot to this project.') !!} </p>
      @endif
  </section>

  @include('project.partials.project-table', $project)

@endsection

resources/views/project/store.blade.php
@extends('layouts.master')

@section('content')
  <h2>Store</h2>
  {{-- @include('client.partials.index-table', array('clients' => $clients)) --}}
@endsection