app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function ()
{
    return view('welcome');
});


Route::group(['middleware' => ['web']], function ()
{
    // Group Routes
    Route::resource('client', 'ClientController');
    Route::resource('project', 'ProjectController');
    Route::resource('shoot', 'ShootController');
    Route::resource('photo', 'PhotoController');
});


// Route::group(['middleware' => 'web'], function () {
//     Route::get('bar', function () {
//         return csrf_token(); // works
//     });
// });

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function ()
{
    //
});

app/Client.php
<?php

namespace Snapshot;

use Illuminate\Database\Eloquent\Model;
// Bootsttrapper Classes
use Bootstrapper\Facades\Accordion as Accordion;
// Sluggable
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

use Snapshot\SnapshotTraits as SnapshotTraits;

/**
 * Class Client
 * This Model defines a client who requests photography work (projects).
 * @package snapshot
 */
class Client extends Model implements SluggableInterface {
    use SnapshotTraits;
    use SluggableTrait;


    /**
     * Converts the Client name to a URL slug.
     * (http://url.com/client-name)
     * @var array
     */
    protected $sluggable = array(
        "build_from" => "name",
        "save_to" => "slug"
    );

    /**
     *  Defines a one to many relationship with Projects.
     * (one Client requests many Projects)
     */
    public function projects()
    {
        return $this->hasMany('Snapshot\Project');
    }

    /**
     *  Defines a one to many relationship with Projects.
     * (one Client requests many Projects)
     */
    public function shoots()
    {
        return $this->belongsToMany('Snapshot\Shoot');
    }

    /**
     * Defines a one to one relationship with Comments.
     * (one Client has a single Comment)
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function comments()
    {
        return $this->morphOne('\Snapshot\Comment', 'commentable');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace Snapshot\Http\Controllers;

use Illuminate\Http\Request;

use Snapshot\Http\Requests;
use Snapshot\Http\Controllers\Controller;
use Snapshot\Http\Requests\ClientFormRequest;

use Snapshot\Client as Client;
use Snapshot\Comment as Comment;
use Snapshot\Project as Project;
use Snapshot\Shoot as Shoot;
use Snapshot\SnapshotTraits as SnapshotTraits;

class ClientController extends Controller {
    use SnapshotTraits;

    protected $imgPath = "/home/dev/Sites/snapshot.app/resources/assets/images/";

    public function index()
    {
        $clients = Client::all();

        return view('client.index')->with('clients', $clients);
    }

    public function show($id)
    {
        $client = Client::findBySlug($id);

        return view('client.show')->with('client', $client);
    }

    public function create()
    {
        return view('client.create');
    }

    public function edit($id)
    {
        $client = Client::findBySlug($id);

        return view('client.edit')->with('client', $client);
    }

    public function store(ClientFormRequest $request)
    {
        // Create a new Client object
        $client = new Client;
        $client = $this->makeClient($client, $request);
        $client->save();
        // If there's a client comment, add it to the comments table.
        $this->saveComment($client, $request);
        // Create a project if one was included.
        
        // Make a new image directory for the client.
        mkdir($this->imgPath.$client->id);

        $project = $this->createClientProject($client, $request);
        if ($project) $shoot = $this->createProjectShoot($client, $project, $request);

        // Redirect to the newly created client's page.
        return \Redirect::route('client.show', array('slug' => $client->slug))->with('message', "$client->name was created. ");
    }

    public function update($id, ClientFormRequest $request)
    {
        // Get the client from the database and update fields.
        $client = Client::findBySlug($id);
        $client = $this->makeClient($client, $request);
        // Update the client
        $client->update();
        // If there's a submitted comment, update or save it it in the comments table.
        $this->updateComment($client, $request);

        // Redirect to the newly created clients page.
        return \Redirect::route('client.show', array('slug' => $client->slug))->with('message', "$client->name was updated. ");
    }

    public function destroy($id)
    {
        // Get the client from the database to create the message.
        $client = Client::find($id);
        $message = $client->name . " was deleted.";
        $this->deleteDirectory($this->imgPath.$client->id);
        
        // Delete the cient
        Client::destroy($id);

        // Redirect to the client index.
        return \Redirect::route('client.index')->with('message', $message);
    }

    public function createClientProject(Client $client, ClientFormRequest $request) {
        $project = null;
        if ($request->get('projectName'))
        {
            $project = new Project;
            $project->name = $request->get('projectName');
            $client->projects()->save($project);
            mkdir($this->imgPath.$client->id."/".$project->id);
        }

        return $project;
    }

    public function createProjectShoot(Client $client, Project $project, ClientFormRequest $request) {
        // Create a shoot if one was included.
        if ($request->get('shootName') && isset($project))
        {
            $shoot = new Shoot;
            $shoot->name = $request->get('shootName');
            $shoot->user_id = 1;
            $project->shoots()->save($shoot);
            mkdir($this->imgPath.$client->id."/".$project->id."/".$shoot->id);
        }

        return $shoot;
    }

}

resources/views/client/partials/card.blade.php
@extends('partials.card', ['model' => $model, 'cols' => $cols])

@section('title')
    @include('partials.field.client-name', array('client' => $model)) <br>

	@if($model->company)

	  @include('partials.field.client-company', array('client' => $model))

	@endif
@overwrite

@section('card') 
	
<tr>
<td>
@include('partials.field.client-email', array('client' => $model)) <br>
</td>
</tr>
<tr>
<td>
@include('partials.field.client-phone', array('client' => $model))
</td>
</tr>
@overwrite

resources/views/client/partials/form.blade.php
  {{--  Client Name --}}
  {!! InputGroup::withContents(
    Form::text( 'name', Request::get('name'), ['placeholder' => 'Name...', 'id' => 'name', 'class' => 'col-xs-6'] ) )->prepend( '<label for="name">'.Icon::user().'</label>'
  )  !!}
  @include('partials.formError', array('error' => $errors->first('name')))

  {{--  Client Company --}}
  {!! InputGroup::withContents(
    Form::text( 'company', Request::get('company'), ['placeholder' => 'Company...', 'id' => 'company']  ) )->prepend(  '<label for="company">'.Icon::briefcase() .'</label>'
  )  !!}
  @include('partials.formError', array('error' => $errors->first('company')))

  {{--  Client Email --}}
  {!! InputGroup::withContents(
    Form::text( 'email', Request::get('email'), ['placeholder' => 'Email...', 'id' => 'email']  ) )->prepend(  '<label for="email">'.Icon::send() .'</label>'
  )  !!}
  @include('partials.formError', array('error' => $errors->first('email')))

  {{--  Client Phone--}}
  {!! InputGroup::withContents(
    Form::text( 'phone', Request::get('phone'), ['placeholder' => 'Phone...', 'id' => 'phone']  ) )->prepend(  '<label for="phone">'.Icon::phone_alt() .'</label>'
  )  !!}
  @include('partials.formError', array('error' => $errors->first('phone')))

  {{-- Set the Comments Variable To Request--}}
  {{--*/ $comment = Request::get('comment') /*--}}
  {{-- Get stored comments from the database if there are none posted. --}}
  @if (isset($client))
    @if (isset($client->comments->comment) && !Request::get('comment'))
      {{--*/ $comment = $client->comments->comment /*--}}
    @endif
  @endif

  {{--  Client Comments --}}
  {!! InputGroup::withContents(
    Form::textarea( 'comment', $comment, ['placeholder' => 'Client notes...', 'id' => 'comment']   ) )->prepend(  '<label for="notes">'.Icon::comment() .'</label>'
  )  !!}

resources/views/client/partials/index-table.blade.php
<section class="list">

	@foreach($clients as $model)

	    @include('client.partials.card', ['model' => $model, 'cols' => $cols])

	@endforeach

	@include('partials.card-new', ['model' => $model, 'cols' => $cols])

</section>
  

resources/views/client/partials/show-contact.blade.php
<section class=" col-md-4 sidebar">

  @include('partials.sidebar.client', array('client' => $client))

  @include('partials.sidebar.summary', array('model' => $client))

  @include('partials.sidebar.contact', array('model' => $client))

  @include('partials.sidebar.comment', array('model' => $client))
    
</section>

resources/views/client/partials/show-projects.blade.php
<section class="index col-md-8" style="padding:0;">
  <h3>Projects</h3>
      @if( $client->projects->count() )
        @include('project.partials.index-table', ['projects' => $client->projects, 'cols' => 6])
      @else
        <p> There are no projects for this client. </p>
        <p>
        	{{ HTML::link(URL::route('project.create') . '?client_id=' . $client->id, 'Add a new project now.', ["title" => "Add a new project"])}}
	  	</p>
      @endif
</section>

resources/views/client/partials/show-shoots.blade.php
<section class="project-shoots table-responsive">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="col-xs-10"><strong>Shoot Name</strong></th>
        <th class="col-xs-2"></th>
      </tr>
    </thead>
    <tbody>
      @foreach ( $shoots as $shoot )
      <tr>
        <td>
          {{ $shoot->name }}
          <br>

          {{ $shoot->photos->count() }}
          @if ($shoot->photos->count() ==1 )
            photo
          @else
           photos
          @endif
        </td>
        <td>
            {!! Button::withIcon(Icon::search())->asLinkTo('#')!!}
            {!! Button::withIcon(Icon::pencil())->asLinkTo('#')!!}
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>

</section>