app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function ()
{
    return view('welcome');
});


Route::group(['middleware' => ['web']], function ()
{
    // Group Routes
    Route::resource('client', 'ClientController');
    Route::resource('project', 'ProjectController');
    Route::resource('shoot', 'ShootController');
    Route::resource('photo', 'PhotoController');
});


// Route::group(['middleware' => 'web'], function () {
//     Route::get('bar', function () {
//         return csrf_token(); // works
//     });
// });

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function ()
{
    //
});

resources/views/partials/field/client-company.blade.php
@if($client->company)

<a href="{!! URL::route('client.show', ['slug' => $client->slug]) !!}">
	@include('partials.icons.company')
</a>
{!! HTML::link(\URL::route('client.show', ['slug' => $client->slug]), $client->company, ['title' => "View " . $client->displayName() ]);!!}
@endif

resources/views/partials/field/client-email.blade.php
<a href="mailto:{{ $client->email }}" title="Email {{$client->name}}">
	@include('partials.icons.email')
  {{ $client->email }}
</a>

resources/views/partials/field/client-name.blade.php
<a href="{!! URL::route('client.show', ['slug' => $client->slug]) !!}">
	@include('partials.icons.client')
</a>
{!! HTML::link(\URL::route('client.show', ['slug' => $client->slug]), $client->name, ['title' => "View " . $client->displayName() ]);!!}

resources/views/partials/field/client-phone.blade.php
<a href="tel:{!! $client->phone !!}" title="Call {{$client->name}}">
	@include('partials.icons.phone')
	{!! $client->phone !!}
</a>

resources/views/partials/field/photo-count.blade.php
@include('partials.icons.photo')
{{ $model->text_photo_count() }}

resources/views/partials/field/project-count.blade.php
@include('partials.icons.project')
{!! $model->text_project_count() !!}

resources/views/partials/field/project-deadline.blade.php
@include('partials.icons.date')

@if(isset($project->deadline) && $project->deadline->year > 0)
	<em> Due: @date($project->deadline)</em>
@else
	No date set.
@endif

resources/views/partials/field/project-name.blade.php
<a href="{!! URL::route('project.show', ['slug' => $project->slug]) !!}">
	@include('partials.icons.project')
</a>

{!!$project->displayName(1)!!}

resources/views/partials/field/shoot-count.blade.php
@include('partials.icons.shoot')
{!! $model->text_shoot_count() !!}

resources/views/partials/field/shoot-date.blade.php
@include('partials.icons.date')
@if(isset($shoot->date) && $shoot->date->year > 0)
	<em> Date: @date($shoot->date)</em>
@else
	No date set.
@endif

resources/views/partials/field/shoot-location.blade.php
@include('partials.icons.location')
@if($shoot->location)
  <em> {{ $shoot->location }}</em>
@else
	No location set.
@endif

resources/views/partials/field/shoot-name.blade.php
<a href="{!! URL::route('shoot.show', ['slug' => $shoot->slug]) !!}">
@include('partials.icons.shoot')
</a>
{!!$shoot->displayName(1)!!}