app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function ()
{
    return view('welcome');
});


Route::group(['middleware' => ['web']], function ()
{
    // Group Routes
    Route::resource('client', 'ClientController');
    Route::resource('project', 'ProjectController');
    Route::resource('shoot', 'ShootController');
    Route::resource('photo', 'PhotoController');
});


// Route::group(['middleware' => 'web'], function () {
//     Route::get('bar', function () {
//         return csrf_token(); // works
//     });
// });

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function ()
{
    //
});

app/Photo.php
<?php
namespace Snapshot;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Photo
 * This Model defines a photograph which was captured as part of a shoot.
 * It is responsible for adding, retrieving and removing photos from
 * the database AND the server's filesystem.
 *
 * @package snapshot
 */
class Photo extends Model {

    /**
     * Defines a many to one relationship with Shoots.
     * (many Photos are taken during one Shoot)
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function shoot()
    {
        return $this->belongsTo('Snapshot\Shoot');
    }

    /**
     * Defines a many to one relationship with camera.
     * (many Photos are taken by one Camera)
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function camera()
    {
        return $this->belongsTo('Snapshot\Camera');
    }

    /**
     * Defines a many to one relationship with Lens.
     * (many Photos are taken with one Lens)
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function lens()
    {
        return $this->belongsTo('Snapshot\Lens');
    }
}

app/Http/Controllers/PhotoController.php
<?php

namespace Snapshot\Http\Controllers;

use Illuminate\Http\Request;

use Snapshot\Http\Requests;
use Snapshot\Http\Controllers\Controller;
// use Snapshot\Http\Requests\PhotoFormRequest;

use Snapshot\Photo as Photo;
use Snapshot\Shoot as Shoot;
use Snapshot\Project as Project;
use Snapshot\Client as Client;
use Snapshot\Comment as Comment;

class PhotoController extends Controller {
    public function index()
    {
        // $photos = Photo::all();
        return view('photo.index');
    }

    public function show($id)
    {
        // $photo = Photo::findBySlug($id);
        // return view('photo.show')->with('photo', $photo);
    }

    public function create()
    {
        // return view('photo.create');
    }

    public function edit($id)
    {
        // $photo = Photo::findBySlug($id);
        // return view('photo.edit')->with('photo',$photo);
    }

    public function store(PhotoFormRequest $request)
    {
        // // Create a new Client object
        // $photo = new Client;
        // $photo = $this->makeClient($photo, $request);
        // $photo->save();
        // // If there's a photo comment, add it to the comments table.
        // $this->saveComment($photo, $request);
        // Redirect to the newly created photos page.
        return \Redirect::route('photo.show', array('slug' => $photo->slug))->with('message', "$photo->name was created. ");
    }

    public function update($id, PhotoFormRequest $request)
    {
        // // Get the photo from the database and update fields.
        // $photo = Photo::findBySlug($id);
        // $photo = $this->makeClient($photo, $request);
        // // Update the photo
        // $photo->update();
        // // If there's a submitted comment, update or save it it in the comments table.
        // $this->updateComment($photo, $request);
        //

        // Redirect to the newly created photos page.
        return \Redirect::route('photo.show', array('slug' => $photo->slug))->with('message', "$photo->name was updated. ");
    }

    public function destroy($id)
    {
        // // Get the photo from the database to create the message.
        // $photo = Photo::find($id);
        // $message = $photo->name . " was deleted.";
        // // Delete the cient
        // Photo::destroy($id);
        // // Redirect to the photo index.
        // return \Redirect::route('photo.index')->with('message', $message);
    }

    /**
     * Takes a photo and request and populates $photos fields.
     * @method makeClient
     *
     * @param  Client           $photo   A Client object.
     * @param  PhotoFormRequest $request A PhotoFormRequest object
     *
     * @return snapshot/Client            A Client object.
     */
    protected function makeClient(Client $photo, PhotoFormRequest $request)
    {
        $photo->name = $request->get('name');
        $photo->company = $request->get('company');
        $photo->email = $request->get('email');
        $photo->phone = $request->get('phone');

        return $photo;
    }

    protected function saveComment(Client $photo, PhotoFormRequest $request)
    {
        // If there's a photo comment, add it to the comments table.
        if ($request->get('comment'))
        {
            $comment = new Comment;
            $comment->comment = $request->get('comment');
            $photo->comments()->save($comment);
        }
    }

    protected function updateComment(Client $photo, PhotoFormRequest $request)
    {
        // If there is no existing comment, call saveComment() instead.
        if (!isset($photo->comments->id))
        {
            $this->saveComment($photo, $request);

            return;
        }
        // Otherwise, get the existing comment from the database.
        $comment = Comment::find($photo->comments->id);
        // If comment is non-empty, update it.
        if ($request->get('comment'))
        {
            $comment->comment = $request->get('comment');
            $comment->update();

            return;
            // Otherwise, delete it.
        } else
        {
            Comment::destroy($comment->id);

            return;
        }
    }
}

resources/views/photo/create.blade.php
@extends('layouts.master', ["pageTitle" => "Add Client", "subTitle" => "New Client"])

@section('content')
  {!! Form::open(array(
    'route' => 'client.store',
    'class' => 'form'
  ))!!}
  @include('client.partials.form' )

  {!! Button::primary('Create Client!')->submit()->block()!!}
  {!! Form::close() !!}
@endsection

resources/views/photo/delete.blade.php
@extends('layouts.master')

@section('content')
  <h2>Delete</h2>
  {{-- @include('client.partials.index-table', array('clients' => $clients)) --}}
@endsection

resources/views/photo/edit.blade.php
{{--*/
  $subTitle = $client->name;
  if ($client->name && $client->company) {
    $subTitle.= " - ";
  }
  $subTitle.= $client->company;
/*--}}

@extends('layouts.master', ["pageTitle" => "Edit Client", "subTitle" => $subTitle])

@section('content')
  {!! Form::model($client, array(
    'method'=> 'put',
    'route' => ['client.update', $client->slug],
    'class' => 'form',
  )) !!}

  {{ Session::get('message') }}
  @include('client.partials.form')
  {!! Button::primary('Update Client')->submit()->block()!!}
  {!! Form::close() !!}
@endsection

resources/views/photo/index.blade.php
@extends('layouts.master', ['pageTitle' => 'Photos', 'subTitle' => 'All Photos'])

@section('content')
@endsection

resources/views/photo/show.blade.php
{{--*/
  $subTitle = $client->name;
  if ($client->name && $client->company) {
    $subTitle.= " - ";
  }
  $subTitle.= $client->company;
/*--}}

@extends('layouts.master', ["pageTitle" => "Client", "subTitle" => $subTitle])

@section('content')
  <section class="actions">
{{-- Create the delete button --}}
    {{--*/
    $delBtn = Form::open(array('route' => array('client.destroy', $client->id), 'method' => 'delete'));
    $delBtn.= Button::danger(Icon::ok() . " Delete" )->large()->withAttributes(["class" => "col-xs-5 col-xs-push-2"])->submit();
    $delBtn.= Form::close();
    /*--}}


  {!! Button::withIcon(Icon::pencil())->large()->asLinkTo(URL::route('client.edit', array("id" => $client->slug)))->withAttributes(["title" => "Edit $client->name"]) !!}
  {!! Modal::named('button-1')
        ->withTitle(Icon::exclamation_sign() . ' Warning', 'alert-danger')
        ->withBody("
          <p>Are you sure you want to delete $client->name? </p> <p>If you proceed, all projects, shoots and photos for this client will be permanently removed.")
        ->withFooter(
            Button::success(Icon::remove() . " Cancel" )->large()->withAttributes(["data-dismiss" => "modal", "class" => 'col-xs-5']) .
            $delBtn
            )
        ->withButton(Button::danger(Icon::trash())->large()->withAttributes(["title" => "Delete $client->name"])) !!}



  </section>
  @include('client.partials.show-projects', array('client' => $client))
  @include('client.partials.show-contact', array('client' => $client))
@endsection

resources/views/photo/store.blade.php
@extends('layouts.master')

@section('content')
  <h2>Store</h2>
  {{-- @include('client.partials.index-table', array('clients' => $clients)) --}}
@endsection